exp_dir:
hydra:
  run:
    dir: ${exp_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

tokenizer: facebook/bart-base

model:
  model_type: audio-caption
  audio_encoder:
    model_type: zipformer
    pretrained_model: null
    frozen: False

trainer:
  optimizer:
    type: scaled_adam
    lr: 0.045
  scheduler:
    type: eden
    lr_epochs: 3.5
    lr_batches: 7500
    warmup_batches: 500
    lr_steps_per_epoch: 0
  start_epoch: 1
  num_epochs: 30
  start_batch: 0
  num_steps: 300000
  keep_last_k: 30
  use_averaged_model: True
  log_interval: 50
  average_period: 200
  reset_interval: 200
  valid_interval: 1000
  save_every_n: 4
  use_fp16: False
  tensorboard: True
  parallel_decoding_prob: 0.0
  max_length: 128

data:
  train_data_config: configs/data_configs/train_data_config.yaml
  valid_data_config: configs/data_configs/valid_data_config.yaml
  on_the_fly_feats: True
  sampling_rate: 16000
  num_workers: 8
  pad_to_30s: False
  use_infinite_dataset: True
  data_augmentation:
    enable_spec_aug: True
    enable_musan: False
    musan: your_path_to_musan_cuts.jsonl.gz
    enable_speed_perturb: False
  tag_field: audio_tag
  caption_field: caption
  sampler:
    type: bucketing_sampler
    num_buckets: 30
    max_duration: 600
    shuffle: True
    drop_last: True
